server:
  port: 18090
spring:
  application:
    name: icore-config-server
  cloud:
    config:
      server:
        git:
          uri: http://10.88.2.63:28080/icoreConfig/icoreConfig.git
          search-paths: config
          username: icoreConfig
          password: icoreConfig
  rabbitmq:
    addresses: 10.88.2.62:5672
    username: icoreBus
    password: icoreBus
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.31.116:18080/eureka/
logging:
  config: classpath:log.xml